import { TeacherEmailCredentialNotice } from '../types';
import { Storage } from '../utils/storage';
import { sendGmailMessage } from './googleWorkspace';

/**
 * Automated Email Service for RITE-OS Faculty Identity & Account Security
 * Generates and securely dispatches temporary passwords to registered teachers' email addresses
 * for initial account access verification.
 */

export function generateTeacherTemporaryPassword(role: 'teacher' | 'hod' = 'teacher'): string {
  const prefix = role === 'hod' ? 'RITE#Hod' : 'RITE#Tch';
  // 5-digit high entropy cryptographically random number
  const array = new Uint32Array(1);
  if (typeof window !== 'undefined' && window.crypto) {
    window.crypto.getRandomValues(array);
    const code = 10000 + (array[0] % 90000);
    return `${prefix}${code}`;
  }
  const code = Math.floor(10000 + Math.random() * 90000);
  return `${prefix}${code}`;
}

export interface DispatchTemporaryPasswordParams {
  teacherEmail: string;
  teacherName: string;
  facultyId: string;
  department: string;
  role: 'teacher' | 'hod';
  customTempPassword?: string;
}

export interface DispatchTemporaryPasswordResult {
  success: boolean;
  temporaryPassword: string;
  notice: TeacherEmailCredentialNotice;
  messageId?: string;
  error?: string;
}

export async function sendTeacherTemporaryPasswordEmail({
  teacherEmail,
  teacherName,
  facultyId,
  department,
  role,
  customTempPassword,
}: DispatchTemporaryPasswordParams): Promise<DispatchTemporaryPasswordResult> {
  const tempPassword = customTempPassword || generateTeacherTemporaryPassword(role);
  const now = new Date().toISOString();
  const subject = `Welcome to RITE-OS — Initial Account Credentials & Temporary Password`;

  const emailBody = `Dear ${teacherName || 'Faculty Colleague'},

Welcome to Radhakrishna Institute of Technology & Engineering (RITE-OS).

Your official academic account has been registered in the Institutional Governance Directory.
To secure your initial account access, your temporary password has been automatically generated by the RITE Automated Security Service:

================================================================================
OFFICIAL FACULTY CREDENTIALS FOR INITIAL LOGIN:
--------------------------------------------------------------------------------
• Portal Identifier / Email: ${teacherEmail}
• Assigned Faculty ID:       ${facultyId}
• Temporary Password:        ${tempPassword}
• Department:                ${department}
• Designation / Role:        ${role === 'hod' ? 'Head of Department (HOD)' : 'Faculty Teacher'}
================================================================================

MANDATORY SECURITY INSTRUCTIONS:
1. Navigate to the RITE-OS Login Portal: select '${role === 'hod' ? 'HOD' : 'Teacher'}' mode.
2. Sign in using your registered Faculty ID (${facultyId}) or Email (${teacherEmail}) and the temporary password above.
3. For institutional data security, this temporary password secures your initial access. You may change your password under your account profile settings once logged in.
4. Keep this communication strictly confidential. Do not share your temporary credentials with students or unauthorized personnel.

If you did not initiate this faculty registration, please immediately contact the Academic Registrar (admin@riteindia.edu.in).

Warm regards,
Automated Identity & Security Directorate
Radhakrishna Institute of Technology & Engineering (RITE)
Campus Security & Identity Verification Service`;

  const notice: TeacherEmailCredentialNotice = {
    id: `cred-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
    teacherEmail: teacherEmail.trim().toLowerCase(),
    teacherName: teacherName.trim(),
    facultyId,
    department,
    role,
    temporaryPassword: tempPassword,
    sentAt: now,
    status: 'dispatched',
    subject,
  };

  // 1. Persist notice into local storage for quick access & UI feedback
  Storage.saveTeacherCredentialEmail(notice);

  // 2. Dispatch via backend endpoint (server.ts automated service)
  let backendMessageId: string | undefined;
  try {
    const res = await fetch('/api/auth/send-teacher-temp-password', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        teacherEmail,
        teacherName,
        facultyId,
        department,
        role,
        temporaryPassword: tempPassword,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      backendMessageId = data.messageId;
      notice.messageId = data.messageId;
      notice.status = 'delivered';
      Storage.saveTeacherCredentialEmail(notice);
    }
  } catch (err) {
    console.warn('Backend email endpoint connection fallback:', err);
  }

  // 3. Dispatch through Gmail integration service (appears in Gmail outbox/sent items)
  try {
    await sendGmailMessage({
      to: teacherEmail,
      subject,
      body: emailBody,
    });
  } catch (err) {
    console.warn('Gmail API automated dispatch log fallback:', err);
  }

  return {
    success: true,
    temporaryPassword: tempPassword,
    notice,
    messageId: backendMessageId || notice.id,
  };
}
